<img src="http://www.cs.wm.edu/~rml/images/wm_horizontal_single_line_full_color.png">

<h1 style="text-align:center;">CSCI 420: Introduction to Machine Learning final exam</h1>
<h1 style="text-align:center;">Problem 3</h1>
<h1 style="text-align:center;">Due by 1700 on Tuesday, December 12, 2017</h1>

# Name: be sure to write your name here

# Building a classifier for the 2016 presidential election

In this problem you will look at county-level data for the 2016 presidential election ("county" is used loosely here, since Virginia has independent cities that are also included in the data).

The goal is to build a classifier to determine whether a county voted for Clinton or for Trump.

The demographic and geographic features for each county are [listed below](#Extract-the-features).

An interesting feature of the election was the so-called [Clinton Archipelago](http://www.vividmaps.com/2016/12/trumpland-and-clinton-archipelago.html): Clinton carried relatively few counties compared to Trump (but they were counties with large populations):
<pre>
Class breakdown:  training set  test set  total
       Clinton       330          158       488
         Trump      1670          954      2624
</pre>

The simplest classifier we can build from the training data would be to say all counties vote Trump.  This classifier would be correct for  
$$
  1 - \frac{330}{330 + 1670} = 83.5\%
$$
of the training cases, and
$$
1 - \frac{158}{158 + 954} = 85.8\%
$$
of the test cases!  So whatever classifier we build must do substantially better than this.

# The data

The training and test data are in [<code>train_vote16.csv</code>](http://www.cs.wm.edu/~rml/teaching/ml/final/train_vote16.csv) and [<code>test_vote16.csv</code>](http://www.cs.wm.edu/~rml/teaching/ml/final/test_vote16.csv), respectively.  These are CSV files.

Column 0 is the class label:
<pre>
0: won by Clinton
1: won by Trump
</pre>

The next two columns are the actual number of votes from 2016.  We won't use those &ndash; that would be cheating!

The next three columns are:
<pre>
state_abbr:  the state's abbreviation
county_name: the name of the county or city
state_fips:  the Federal Information Processing Standards code for the state
FIPS:        the Federal Information Processing Standards code for the county or city
</pre>

These are followed by information about the 2012 election, including the proportion voting for Obama and Romney as well as the vote totals themselves:
<pre>
total_votes_2012: total number of votes cast in the 2012 election
votes_dem_2012:   number of votes cast for the Democratic candidate in 2012
votes_rep_2012:   number of votes cast for the Republican candidate in 2012
Obama:            percentage voting for Obama in 2012
Romney:           percentage voting for Romney in 2012
</pre>

The remaining columns are demographic data about the county or city:
<pre>
PST045214: Population, 2014 estimate
PST040210: Population, 2010 (April 1) estimates base
PST120214: Population, percent change - April 1, 2010 to July 1, 2014
POP010210: Population, 2010
AGE135214: Persons under 5 years, percent, 2014
AGE295214: Persons under 18 years, percent, 2014
AGE775214: Persons 65 years and over, percent, 2014
SEX255214: Female persons, percent, 2014
RHI125214: White alone, percent, 2014
RHI225214: Black or African American alone, percent, 2014
RHI325214: American Indian and Alaska Native alone, percent, 2014
RHI425214: Asian alone, percent, 2014
RHI525214: Native Hawaiian and Other Pacific Islander alone, percent, 2014
RHI625214: Two or More Races, percent, 2014
RHI725214: Hispanic or Latino, percent, 2014
RHI825214: White alone, not Hispanic or Latino, percent, 2014
POP715213: Living in same house 1 year & over, percent, 2009-2013
POP645213: Foreign born persons, percent, 2009-2013
POP815213: Language other than English spoken at home, pct age 5+, 2009-2013
EDU635213: High school graduate or higher, percent of persons age 25+, 2009-2013
EDU685213: Bachelor's degree or higher, percent of persons age 25+, 2009-2013
VET605213: Veterans, 2009-2013
LFE305213: Mean travel time to work (minutes), workers age 16+, 2009-2013
HSG010214: Housing units, 2014
HSG445213: Homeownership rate, 2009-2013
HSG096213: Housing units in multi-unit structures, percent, 2009-2013
HSG495213: Median value of owner-occupied housing units, 2009-2013
HSD410213: Households, 2009-2013
HSD310213: Persons per household, 2009-2013
INC910213: Per capita money income in past 12 months (2013 dollars), 2009-2013
INC110213: Median household income, 2009-2013
PVY020213: Persons below poverty level, percent, 2009-2013
BZA010213: Private nonfarm establishments, 2013
BZA110213: Private nonfarm employment,  2013
BZA115213: Private nonfarm employment, percent change, 2012-2013
NES010213: Nonemployer establishments, 2013
SBO001207: Total number of firms, 2007
SBO315207: Black-owned firms, percent, 2007
SBO115207: American Indian- and Alaska Native-owned firms, percent, 2007
SBO215207: Asian-owned firms, percent, 2007
SBO515207: Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007
SBO415207: Hispanic-owned firms, percent, 2007
SBO015207: Women-owned firms, percent, 2007
MAN450207: Manufacturers shipments, 2007 ($1,000)
WTN220207: Merchant wholesaler sales, 2007 ($1,000)
RTN130207: Retail sales, 2007 ($1,000)
RTN131207: Retail sales per capita, 2007
AFN120207: Accommodation and food services sales, 2007 ($1,000)
BPS030214: Building permits, 2014
LND110210: Land area in square miles, 2010
POP060210: Population per square mile, 2010
</pre>

# To Do

* Build a classifier that predicts how a county votes with at least 97% overall accuracy.  It isn't too difficult to obtain 98% overall accuracy, and at least 95% accuracy for each candidate.  More accurate is better for this problem.
* Populate this Jupyter notebook with the code needed to create, train, and run your CNN.
    * As part of your model evaluation, your notebook should compute and print the confusion matrix and f1-scores.
* You should build your classifier and any preprocessing as a scikit-learn <code>Pipeline</code>.
* You should save your classification pipeline to the file <code>vote16_clf.pkl</code> using <code>sklearn.externals.joblib</code> (see below).
* If you use a grid search or random search for hyperparameter tuning, you should indicate this in the write-up below, and submit the hyperparameters used in the submitted solution (you can just specify them in calls to the classifier's constructor).
* If you try a classifier and it does not work to your liking, you should indicate this.  You can leave the code in the notebook, commented out, so I can see what you tried.

* You can choose from any of the classifiers we studied, including
 - [k nearest neighbors](http://scikit-learn.org/stable/modules/neighbors.html),
 - [support vector machines / kernel machines](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html),
 - [decision trees](http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier),
 - [logistic regression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html),
 - [neural networks](http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier) (you will need scikit-learn 0.18 for this; use <code>conda update scikit-learn</code>),
 - ensembles of the preceding (i.e., [random forests](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) and [AdaBoosted collections of weak learners](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html)),
 - [neural networks](http://scikit-learn.org/stable/modules/neural_networks_supervised.html)
 
## Note

In order to build a pipeline you will need to implement your own first step of the pipeline in order to perform feature selection and any necessary feature encoding.  You can do so by creating your own class with a <code>fit()</code> and <code>transform()</code> method.  

The calling sequences and return sequences of these two methods should be the same as those of the StandardScaler [<code>fit()</code>](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler.fit) and [<code>transform()</code>](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler.transform).

For example, <code>fit()</code> might not do anything while <code>transform()</code> will return a subset of the variables as a numpy array.

For full credit your pipeline should encapsulate all of your preprocessing steps.  If you cannot figure out how to make this work, you can enter your preprocessing steps below.

# Questions to answer

1. What classifiers did you try?
2. What tuning did you do?
3. How did the classifiers perform?
4. If you end up with a decision tree, explain how the tree makes its decisions.  For other classifiers, try to give some insight into why it works.
5. What is cross-validation, and how can it be used in constructing classifiers?

# What to submit

1. This Jupyter notebook, filled out with code that when run will produce a working classifer with all necessary preprocessing.
    * You should use your final hyperparameter values in the call to the classifier's constructor.
2. If you get the pipeline working, the resulting <code>.pkl</code> file.

<br/><br/>

# Your code follows

You are free to change the section titles, add sections, &amp;c.

# Read the data

In [67]:
import pandas as pd
import numpy  as np

print('reading data...', end='')
df_train = pd.read_csv('train_vote16.csv')
df_test  = pd.read_csv('test_vote16.csv')
print('done!')

x_train = df_train.iloc[:,3:]
x_test  = df_test.iloc[:,3:]

y_train = df_train.iloc[:,0]
y_test  = df_test.iloc[:,0]




#print(type(x_train))
#print(y_train)
#print(y_test)


#print(x_train)
#print(x_test)
frames = [x_train,x_test]
result = pd.concat(frames)
result_with_dummies = pd.get_dummies(result,columns=["state_abbr","county_name"],drop_first=False)
#print(result)
#print(result_with_dummies)
#print(list(result_with_dummies))
n = 2000
x_train_dum = result_with_dummies[:n]
x_test_dum = result_with_dummies[n:]
#print(x_train_dum)
#print(x_test_dum)

x_train_new = x_train_dum.as_matrix(columns=None)
x_test_new = x_test_dum.as_matrix(columns=None)

x_train_new = np.array(list(x_train_new))
x_test_new = np.array(list(x_test_new))


print(x_train_new)
print(x_test_new)
print(x_train_new.shape)
print(x_test_new.shape)



y_train_new = y_train.as_matrix(columns=None)
y_test_new = y_test.as_matrix(columns=None)


y_train_new = np.array(list(y_train_new))
y_test_new = np.array(list(y_test_new))

print(y_train_new)
print(y_test_new)
print(y_train_new.shape)
print(y_test_new.shape)
print(y_test_new.ndim)











reading data...done!
[[ 19073.   4804.   2369. ...,      0.      0.      0.]
 [ 13119.   7757.   1499. ...,      0.      0.      0.]
 [ 37133.  50353.  18115. ...,      0.      0.      0.]
 ..., 
 [ 13193.   4781.   3211. ...,      0.      0.      0.]
 [ 46039.   2171.    941. ...,      0.      0.      0.]
 [ 13269.   3537.   1571. ...,      0.      0.      0.]]
[[ 18095.  52340.  24404. ...,      0.      0.      0.]
 [ 22121.  12772.   5692. ...,      0.      0.      0.]
 [ 27055.  10422.   5281. ...,      0.      0.      0.]
 ..., 
 [ 22095.  21122.  13178. ...,      0.      0.      0.]
 [ 27021.  16080.   6858. ...,      0.      0.      0.]
 [ 20005.   6499.   2486. ...,      0.      0.      0.]]
(2000, 1954)
(1112, 1954)
[ 1.  1.  1. ...,  0.  1.  1.]
[ 1.  1.  1. ...,  0.  1.  1.]
(2000,)
(1112,)
1


# Specify the classification pipeline

# Train the classifier

In [74]:
import numpy as np
from sklearn import metrics

def compute_metrics (classifier, X_test, y_test):
    """
    This function computes and prints various performance measures for a classifier.
    """
    # Use the classifier to make predictions for the test set.
    y_pred = classifier.predict(X_test)
    
    # Choose the class with the highest estimated probability.
    #y_pred = np.argmax(y_pred, axis=0)



    # Compute the confusion matrix.
    cm = metrics.confusion_matrix(y_test, y_pred)
    print('Confusion matrix, without normalization')
    print(cm, '\n')

    # Normalize the confusion matrix by row (i.e by the number of samples in each class).
    cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
    np.set_printoptions(precision=3, linewidth=132)
    print('Normalized confusion matrix')
    print(cm_normalized, '\n')

    # The confusion matrix as percentages.
    cm_percentage = 100 * cm_normalized
    print('Confusion matrix as percentages')
    print(np.array2string(cm_percentage, formatter={'float_kind':lambda x: "%6.2f" % x}), '\n')
    
    # Precision, recall, and f-score.
    print(metrics.classification_report(y_test, y_pred, digits=3))

    return cm

In [75]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix


scaler = StandardScaler()

X_train_fit = scaler.fit_transform(x_train_new)
X_test_fit = scaler.fit_transform(x_test_new)

#svm = SVC(kernel='rbf', C=100.0, gamma=0.01,random_state=0)
#Svc = svm.fit(X_train_fit,y_train_new)
# 0.85701438848920863 accuracy

#lr = LogisticRegression(C=100.0, random_state=0)
#log_reg = lr.fit(X_train_fit, y_train_new)
# 0.91276978417266186

tree = DecisionTreeClassifier(criterion='entropy', max_depth=6, random_state=0)
dec_tree = tree.fit(X_train_fit, y_train_new)
# 0.97122302158273377 with depth 7
# 0.9730215827338129  with depth 6
# 0.97212230215827333 with depth 5

#knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
#KNN = knn.fit(X_train_fit, y_train_new)
# 0.89928057553956831

#compute_metrics(Svc, X_test_fit, y_test_new)
y_pred = dec_tree.predict(X_test_fit)
print(metrics.accuracy_score(y_test_new,y_pred))

#print(confusion_matrix(y_test_new, y_pred))

compute_metrics(Svc, X_test_fit, y_test_new)




0.973021582734
Confusion matrix, without normalization
[[  1 157]
 [  2 952]] 

Normalized confusion matrix
[[ 0.006  0.994]
 [ 0.002  0.998]] 

Confusion matrix as percentages
[[  0.63  99.37]
 [  0.21  99.79]] 

             precision    recall  f1-score   support

        0.0      0.333     0.006     0.012       158
        1.0      0.858     0.998     0.923       954

avg / total      0.784     0.857     0.794      1112



array([[  1, 157],
       [  2, 952]])

In [73]:
print(y_pred)
print(y_pred.shape)
print(y_test.shape)

[ 1.  1.  1. ...,  0.  1.  1.]
(1112,)
(1112,)


# Evaluate the classifier

# Save the classification pipeline

&hellip;assuming it is named <code>clf</code>&hellip;

In [ ]:
from sklearn.externals import joblib

print('Saving the classifier...')
joblib.dump(clf, 'vote16_clf.pkl')